defaults:
  - experiment: base_experiment
  - algorithm@algs.a1: ippo
  - algorithm@algs.a2: ippo/tuned
  - algorithm@algs.a3: mappo
  - task@tasks.t1: pettingzoo/multiwalker
  - task@tasks.t2: multiwalker/shared
  - model: layers/mlp
  - model@critic_model: layers/mlp
  - _self_

hydra:
  searchpath:
    - pkg://benchmarl/conf

experiment:
  save_folder: "results/benchmarks/multiwalker/"

clean_folder: false
train: true
plot: true
interactive: true
seeds:
  - 0
  - 1
