defaults:
  - experiment: base_experiment
  - algorithm: ???
  - task: ???
  - model: layers/mlp
  - model@critic_model: layers/mlp
  - _self_

hydra:
  searchpath:
    - pkg://benchmarl/conf

experiment:
  save_folder: "results/experiments"

clean_folder: false
train: true
plot: true
interactive: true
seed: 0
