defaults:
  - experiment: debug
  - algorithm: qmix/default
  - task: kaz/default
  - model: mlp/default
  - model@critic_model: mlp/default
  - _self_

task:
  shared_reward: true

clean_folder: false
train: true
plot: true
interactive: true
seed: 0
