defaults:
  - experiment: base_experiment
  - algorithm@algs.a1: ???
  - task@tasks.t1: ???
  - model: layers/mlp
  - model@critic_model: layers/mlp
  - _self_

hydra:
  searchpath:
    - pkg://benchmarl/conf
  run:
    dir: results/hydra/${hydra.job.name}-run/${now:%Y-%m-%d_%H-%M-%S}

experiment:
  save_folder: "results/benchmarks"
  project_name: "marl-cluster-training"
  wandb_extra_kwargs:
    project: "marl-cluster-training"
    entity: "yp-edu"

clean_folder: false
train: true
plot: true
plot_environment: null
interactive: true
seeds:
  - 0
  - 1
  - 2
run_specific_expirment: null
