defaults:
  - experiment: base_experiment
  - algorithm: ???
  - task: ???
  - model: layers/mlp
  - _self_

critic_model: ${model}

hydra:
  searchpath:
    - pkg://benchmarl/conf
  sweep:
    dir: results/hydra/${hydra.job.name}-sweep/${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: results/hydra/${hydra.job.name}-run/${now:%Y-%m-%d_%H-%M-%S}

experiment:
  save_folder: "results/experiments"
  project_name: "marl-cluster-training"
  wandb_extra_kwargs:
    project: "marl-cluster-training"
    entity: "yp-edu"

clean_folder: false
train: true
plot: true
interactive: false
seed: 0
