defaults:
  - pettingzoo_kaz_config
  - _self_

task: "knights_archers_zombies_v10"
spawn_rate: 20
num_archers: 2
num_knights: 2
max_zombies: 10
max_arrows: 10
killable_knights: true
killable_archers: true
pad_observation: true
line_death: false
max_cycles: 900
vector_state: false
use_typemasks: false
sequence_space: false
