defaults:
  - ippo_config
  - _self_

share_param_critic: True
clip_epsilon: 0.3
entropy_coef: 0.5
critic_coef: 0.5
loss_critic_type: "l2"
lmbda: 0.9
scale_mapping: "biased_softplus_1.0"
use_tanh_normal: True
minibatch_advantage: False
